### ISSUE TITLE
code can be much shorter

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [kevinkabatra/PHP-API-Key-Generator#1]
```
$output = '';
        for($loop = 0; $loop <= 31; $loop++) {
            for($isRandomInRange = 0; $isRandomInRange === 0;){
                $mRandom = mt_rand(48,122);
                $isRandomInRange = (($mRandom >=58 && $mRandom <= 64) || (($mRandom >=91 && $mRandom <= 96))) ? 0 : $mRandom;
            }
            $output .= chr($isRandomInRange);
        }
        echo $output;
```

**Comment by kevinkabatra** [comment]
Howdee.

Thanks for the comment.

I would ask is it important to have the code be of shorter length? In some embedded systems where memory can be limited I could see the value in having something less verbose. But generally I personally would prefer to use functions to clearly separate the code and to enable testing of the various components. Except in the case where changing the source would offer a notable increase in performance. Of course that would depend on the scale at which you were deploying the code.

I think it is really a matter of preference and the benefit of the license is that you could fork this repository and do what you want with it. I added two links below that point to completely opposite philosophies. Perl is all about do it how you see fit, while Python prefers a more concise approach.

1. https://en.m.wikipedia.org/wiki/There%27s_more_than_one_way_to_do_it

2. https://en.m.wikipedia.org/wiki/Zen_of_Python

**Comment by 24HOURSMEDIA** [comment]
ok you're right, it's not really an issue anyway.
thanks for posting on github
